global:
  scrape_interval: 10s

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - localhost:9093

rule_files :
  - 'rules.yml'

scrape_configs:
  - job_name: 'nodes'
    ec2_sd_configs:
      - region: ap-south-1
        access_key: AKIARZOVXQHRKNYOTUN6
        secret_key: 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
        port: 9100
  - job_name: 'nginx'
    ec2_sd_configs:
      - region: ap-south-1
        access_key: AKIARZOVXQHRKNYOTUN6
        secret_key: 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
        port: 9113
    relabel_configs:
      - source_labels: [__meta_ec2_tag_Name]
        regex: Xalts.*
        action: keep
          # Use the instance ID as the instance label
      - source_labels: [__meta_ec2_instance_id]
        target_label: instance

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]  
    static_configs:
      - targets:
        - http://43.205.115.137:8081/index.html    
        - https://43.205.115.137:8081/about.html   
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9115  
  - job_name: 'blackbox_exporter' 
    static_configs:
      - targets: ['localhost:9115']
    
