global:
  scrape_interval: 10s

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - localhost:9093

rule_files :
  - 'rules.yml'

scrape_configs:
  - job_name: 'nodes'
    ec2_sd_configs:
      - region: ap-south-1
        access_key: AKIARZOVXQHRKNYOTUN6
        secret_key: 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
        port: 9100
  - job_name: 'nginx'
    ec2_sd_configs:
      - region: ap-south-1
        access_key: AKIARZOVXQHRKNYOTUN6
        secret_key: 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
        port: 9113
    relabel_configs:
      - source_labels: [__meta_ec2_tag_Name]
        regex: Xalts.*
        action: keep
          # Use the instance ID as the instance label
      - source_labels: [__meta_ec2_instance_id]
        target_label: instance
    
