groups:
- name: node_exporter_alerts
  rules:
  - alert: Node down
    expr: up{job="nodes"} == 0
    for: 1m
    labels:
      severity: warning
    annotations:
      title: Node {{ $labels.instance }} is down
      description: Failed to scrape {{ $labels.job }} on {{ $labels.instance }} for more than 1 minutes. Node seems down.
